# Generated by Django 4.1.1 on 2022-10-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_exercise_exercisereps_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingunit',
            old_name='accesoryexercises',
            new_name='Exercises',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercisereps',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercisesets',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
