# Generated by Django 4.1.1 on 2022-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_accesoryexercises_trainingunit_exercises_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainingunits', models.ManyToManyField(to='core.trainingunit')),
            ],
        ),
    ]
