# Generated by Django 4.1.1 on 2022-10-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trainingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingunit',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
