# Generated by Django 4.1.1 on 2022-10-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trainingunit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='nameoftheplan',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
