# Generated by Django 4.1.1 on 2022-10-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_trainingunit_benchpress1rm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingunit',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
