# Generated by Django 4.1.1 on 2022-10-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_trainingunit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercisename',
            field=models.CharField(choices=[('Bent press', 'Bent press'), ('Windmill', 'Windmill'), ('Rows', 'Rows')], max_length=100, verbose_name='Exercise'),
        ),
    ]
