# Generated by Django 4.1.1 on 2022-10-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_exercise_exercisename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingunit',
            name='user',
        ),
    ]
