# Generated by Django 4.1.1 on 2022-10-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_trainingunit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='timeoftheplan',
            field=models.CharField(choices=[('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('4 Weeks', '4 Weeks')], default='3 Weeks', max_length=40),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='mesocycle',
            field=models.CharField(choices=[('General physical preparation phase', 'GPP'), ('Acumulation phase', 'ACC'), ('Peak phase', 'PEAK'), ('Casual Training', 'Casual training'), ('None', 'None')], default='General physical preparation phase', max_length=40),
        ),
    ]
