# Generated by Django 4.1.1 on 2022-10-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_trainingplan_exercises_trainingplan_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='Exercises',
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mainuserprofile'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='Exercises',
            field=models.ManyToManyField(to='core.exercise'),
        ),
    ]
