# Generated by Django 4.1.1 on 2022-10-28 11:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_trainingplan_exercises_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='Exercises',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='Exercises',
            field=models.CharField(choices=[('Bent press', 'Bent press'), ('Windmill', 'Windmill'), ('Rows', 'Rows')], default=1, max_length=50, verbose_name=core.models.Exercise),
            preserve_default=False,
        ),
    ]
