# Generated by Django 4.1.1 on 2022-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_trainingplan_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='Exercises',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='Exercises',
            field=models.ManyToManyField(null=True, to='core.exercise'),
        ),
    ]
