# Generated by Django 4.1.1 on 2022-10-28 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_trainingplan_exercises_trainingplan_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='Exercises',
        ),
        migrations.AddField(
            model_name='exercise',
            name='trainingplan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.trainingplan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercisename',
            field=models.CharField(choices=[('Bent press', 'Bent press'), ('Windmill', 'Windmill'), ('Rows', 'Rows'), ('Overhead Press', 'Overhead Press')], max_length=100, verbose_name='Exercise'),
        ),
    ]
