# Generated by Django 4.1.1 on 2022-10-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_trainingplan_exercises_exercise_trainingplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.mainuserprofile'),
            preserve_default=False,
        ),
    ]
