# Generated by Django 4.1.1 on 2022-10-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_exercise_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
    ]
