# Generated by Django 4.1.1 on 2022-10-30 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_exercise_exercisename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='trainingplan',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercisename',
            field=models.CharField(choices=[('Overhead Press - bilateral', 'Overhead Press - bilateral'), ('Overhead Press - unilateral', 'Overhead Press - unilateral'), ('Windmill', 'Windmill'), ('Rows', 'Rows'), ('Overhead Press - bilateral', 'Overhead Press'), ('Bent press', 'Bent press')], max_length=100, verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='Benchpress1RM',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='100%RM maximal repetition in benchpress'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='DeadliftT1RM',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='100%RM maximal repetition in deadlift'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='Squat1RM',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='100%RM in squat'),
        ),
        migrations.CreateModel(
            name='TrainingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainingplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainingplan')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='trainingunit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.trainingunit'),
            preserve_default=False,
        ),
    ]
