# Generated by Django 4.1.1 on 2022-10-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_exercise_trainingplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainexercise', models.CharField(choices=[('Squat', 'Squat'), ('Deadlift', 'Deadlift'), ('Benchpress', 'Benchpress')], max_length=100, verbose_name='Exercise')),
                ('trainingunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainingunit')),
            ],
        ),
    ]
