# Generated by Django 4.1.1 on 2022-10-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_mainexercise_maximalrepetition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='Benchpress1RM',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='DeadliftT1RM',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='Squat1RM',
        ),
    ]
