# Generated by Django 4.1.1 on 2022-10-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_mainexercise_trainingunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='Benchpress1RM',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='100%RM maximal repetition in benchpress'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='DeadliftT1RM',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='100%RM maximal repetition in deadlift'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='Squat1RM',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='100%RM in squat'),
        ),
        migrations.AlterField(
            model_name='mainexercise',
            name='mainexercise',
            field=models.CharField(choices=[('Squat', 'Squat'), ('Deadlift', 'Deadlift'), ('Benchpress', 'Benchpress')], max_length=100, verbose_name='Main Exercise'),
        ),
    ]
