# Generated by Django 4.1.1 on 2022-10-31 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_trainingplan_benchpress1rm_trainingplan_deadliftt1rm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='trainingunit',
        ),
        migrations.AddField(
            model_name='exercise',
            name='trainingplan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.trainingplan'),
            preserve_default=False,
        ),
    ]
