# Generated by Django 4.1.1 on 2022-10-31 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_exercise_trainingunit_exercise_trainingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTrainingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercisename', models.CharField(choices=[('Overhead Press - bilateral', 'Overhead Press - bilateral'), ('Overhead Press - unilateral', 'Overhead Press - unilateral'), ('Windmill', 'Windmill'), ('Rows', 'Rows'), ('Overhead Press - bilateral', 'Overhead Press'), ('Bent press', 'Bent press')], max_length=100, verbose_name='Exercise')),
                ('exercisesets', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)])),
                ('exercisereps', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)])),
                ('trainingunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainingunit')),
            ],
        ),
    ]
