# Generated by Django 4.1.1 on 2022-11-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_trainingunit_name_alter_exercise_exercisereps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetrainingunit',
            name='trainingplan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.trainingplan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercisetrainingunit',
            name='exercisename',
            field=models.CharField(choices=[('Overhead Press - bilateral', 'Overhead Press - bilateral'), ('Overhead Press - unilateral', 'Overhead Press - unilateral'), ('Windmill', 'Windmill'), ('Rows', 'Rows'), ('Overhead Press - bilateral', 'Overhead Press'), ('Bent press', 'Bent press')], default='Bent press', max_length=100, verbose_name='Exercise'),
        ),
    ]
