# Generated by Django 4.1.1 on 2022-11-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_exercisetrainingunit_trainingplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisetrainingunit',
            name='trainingplan',
        ),
    ]
