# Generated by Django 4.1.1 on 2022-11-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_exercisetrainingunit_trainingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingunit',
            name='accesoryIIIexercisereps',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], default=1),
        ),
        migrations.AddField(
            model_name='trainingunit',
            name='accesoryIIIexercisesets',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
        migrations.AddField(
            model_name='trainingunit',
            name='accesoryIIexercisereps',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], default=1),
        ),
        migrations.AddField(
            model_name='trainingunit',
            name='accesoryIIexercisesets',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
        migrations.AddField(
            model_name='trainingunit',
            name='accesoryIexercisereps',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], default=1),
        ),
        migrations.AddField(
            model_name='trainingunit',
            name='accesoryIexercisesets',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
        migrations.AddField(
            model_name='trainingunit',
            name='accesoryexerciseI',
            field=models.CharField(choices=[('Overhead Press - bilateral', 'Overhead Press - bilateral'), ('Overhead Press - unilateral', 'Overhead Press - unilateral'), ('Windmill', 'Windmill'), ('Rows', 'Rows'), ('Overhead Press - bilateral', 'Overhead Press'), ('Bent press', 'Bent press')], default='Bent press', max_length=100, verbose_name='Exercise'),
        ),
        migrations.AddField(
            model_name='trainingunit',
            name='accesoryexerciseII',
            field=models.CharField(choices=[('Overhead Press - bilateral', 'Overhead Press - bilateral'), ('Overhead Press - unilateral', 'Overhead Press - unilateral'), ('Windmill', 'Windmill'), ('Rows', 'Rows'), ('Overhead Press - bilateral', 'Overhead Press'), ('Bent press', 'Bent press')], default='Windmill', max_length=100, verbose_name='Exercise'),
        ),
        migrations.AddField(
            model_name='trainingunit',
            name='accesoryexerciseIII',
            field=models.CharField(choices=[('Overhead Press - bilateral', 'Overhead Press - bilateral'), ('Overhead Press - unilateral', 'Overhead Press - unilateral'), ('Windmill', 'Windmill'), ('Rows', 'Rows'), ('Overhead Press - bilateral', 'Overhead Press'), ('Bent press', 'Bent press')], default='Overhead press', max_length=100, verbose_name='Exercise'),
        ),
    ]
