# Generated by Django 4.1.1 on 2022-11-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_trainingunit_accesoryiiiexercisereps_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingunit',
            old_name='accesoryexerciseI',
            new_name='accesoryI',
        ),
        migrations.RenameField(
            model_name='trainingunit',
            old_name='accesoryexerciseII',
            new_name='accesoryII',
        ),
        migrations.RenameField(
            model_name='trainingunit',
            old_name='accesoryexerciseIII',
            new_name='accesoryIII',
        ),
        migrations.RenameField(
            model_name='trainingunit',
            old_name='accesoryIIIexercisereps',
            new_name='accesoryIIIreps',
        ),
        migrations.RenameField(
            model_name='trainingunit',
            old_name='accesoryIIIexercisesets',
            new_name='accesoryIIIsets',
        ),
        migrations.RenameField(
            model_name='trainingunit',
            old_name='accesoryIIexercisereps',
            new_name='accesoryIIreps',
        ),
        migrations.RenameField(
            model_name='trainingunit',
            old_name='accesoryIIexercisesets',
            new_name='accesoryIIsets',
        ),
        migrations.RenameField(
            model_name='trainingunit',
            old_name='accesoryIexercisereps',
            new_name='accesoryIreps',
        ),
        migrations.RenameField(
            model_name='trainingunit',
            old_name='accesoryIexercisesets',
            new_name='accesoryIsets',
        ),
    ]
