# Generated by Django 4.1.1 on 2022-11-02 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_accesoryexercisei_trainingunit_accesoryi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='trainingunit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.trainingunit'),
            preserve_default=False,
        ),
    ]
