# Generated by Django 4.1.1 on 2022-11-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_exercise_trainingunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingunit',
            name='accesoryI',
        ),
        migrations.RemoveField(
            model_name='trainingunit',
            name='accesoryII',
        ),
        migrations.RemoveField(
            model_name='trainingunit',
            name='accesoryIII',
        ),
        migrations.RemoveField(
            model_name='trainingunit',
            name='accesoryIIIreps',
        ),
        migrations.RemoveField(
            model_name='trainingunit',
            name='accesoryIIIsets',
        ),
        migrations.RemoveField(
            model_name='trainingunit',
            name='accesoryIIreps',
        ),
        migrations.RemoveField(
            model_name='trainingunit',
            name='accesoryIIsets',
        ),
        migrations.RemoveField(
            model_name='trainingunit',
            name='accesoryIreps',
        ),
        migrations.RemoveField(
            model_name='trainingunit',
            name='accesoryIsets',
        ),
    ]
